# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: dongus58_left
  - board: nice_nano_v2
    shield: dongus58_right
  - board: seeeduino_xiao_ble
    shield: dongus58_dongle

# Debugging enabled
  # - board: seeeduino_xiao_ble
  #   shield: dongus58_dongle
  #   cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #   artifact-name: dongus58_dongle_with_logging

  # - board: nice_nano_v2
  #   shield: dongus58_right
  #   cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #   artifact-name: dongus58_right_with_logging

  # - board: nice_nano_v2
  #   shield: dongus58_left
  #   cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #   artifact-name: dongus58_left_with_logging

# Reset firmware
  # - board: nice_nano_v2
  #   shield: settings_reset
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
