file_format: "1"
id: dongus58
name: Dongus58
type: shield
url: https://github.com/TweetyDaBird/Lotus58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - dongus58_left
  - dongus58_right
  - dongus58_dongle